const PAGE_SIZE = 5;
const ENDPOINT_EVERYTHING = "everything";
const ENDPOINT_TOPHEADLINES = "top-headlines";



module.exports = {
    PAGE_SIZE: PAGE_SIZE,
    ENDPOINT_EVERYTHING: ENDPOINT_EVERYTHING,
    ENDPOINT_TOPHEADLINES: ENDPOINT_TOPHEADLINES
};

